import express from 'express';
import cors from 'cors';
import mongoose from 'mongoose';
import helloController  from "./controllers/hello-controller.js";
import userController   from "./controllers/users-controller.js";
import tuitsController from './controllers/tuits-controller.js';
mongoose.connect('mongodb+srv://lilyh:secretpassword@cluster0.eziud.mongodb.net/myFirstDatabase?retryWrites=true&w=majority');
const app = express();
app.use(cors());
app.use(express.json());
helloController(app);
userController(app);
tuitsController(app);
app.listen(process.env.PORT || 4000);